Shellcheck fixes.

diff --git a/runcdist b/runcdist
--- a/runcdist
+++ b/runcdist
@@ -99,15 +99,15 @@ main() {
    if test "$tag" != ""; then
       test "$(cdist inventory list -H $tag "${items[@]}")" = "" && {
          echo "No hosts match specified tags."; exit 1; }
-      alltags=( $(cdist inventory list | sed -n "s/.* //; s/,/\n/g;p" | sort -u ) )
+      mapfile -t alltags < <( cdist inventory list | sed -n "s/.* //; s/,/\n/g;p" | sort -u )
       ok=1
       for item in "${items[@]}"; do
-         [[ ! " ${alltags[*]} " =~ " ${item} " ]] && { echo "Tag $item not found."; ok=0; }
+         [[ ! " ${alltags[*]} " == *" ${item} "* ]] && { echo "Tag $item not found."; ok=0; }
       done
       test "$ok" -ne 1 && exit 1
    fi
-   CDISTACTION=$CONFIGTYPE cdist config -c "$CDIST_CONFIG_DIR" "${options[@]}" $all $tag ${items[*]}
-   cdistret=$?
+   CDISTACTION=$CONFIGTYPE cdist config -c "$CDIST_CONFIG_DIR" "${options[@]}" $all $tag "${items[@]}"
+   cdistret="$?"
    type cdist-explore-git > /dev/null 2>&1 && cdist-explore-git "${args[*]} (ret ${cdistret})"
    type cdist-inventory > /dev/null 2>&1 && cdist-inventory
    return $cdistret
